In [2]:
import numpy as np
import torch

Dans PyTorch, tout est un tenseur. Débutons par créer un tenseur

In [39]:
x = torch.empty(1)  #Prend son size en argument
y = torch.empty(3)  #Vecteur 1D avec 3 élèments
print(y)
z = torch.empty(2, 2, 3, 3)  #Vecteur 4D
print(z)

tensor([0., 0., 0.])
tensor([[[[2.1715e-18, 1.8888e+31, 4.7414e+16],
          [6.4094e-10, 8.1424e-13, 1.4585e-19],
          [6.4094e-10, 8.1424e-13, 1.4585e-19]],

         [[6.4094e-10, 8.1424e-13, 1.4585e-19],
          [6.4094e-10, 8.1424e-13, 1.4585e-19],
          [6.4094e-10, 8.1424e-13, 1.4585e-19]]],


        [[[1.0663e-08, 1.3028e-11, 1.9388e+17],
          [1.3563e-19, 1.3563e-19, 1.0383e-05],
          [5.2599e+22, 2.6033e-12, 1.0383e-05]],

         [[5.2012e+22, 2.5606e-12, 2.5350e-09],
          [5.4365e+22, 2.6175e-12, 1.0140e-08],
          [5.4373e+22, 8.3401e+17, 3.2304e-18]]]])


In [43]:
x = torch.rand(2,2) #Prend size en argument -> Retourne tenseur random
print(x)
x = torch.zeros(2, 2)  #Équivalent à numpy
x = torch.ones(2,2)
print(x)

tensor([[0.2425, 0.9404],
        [0.5248, 0.5002]])
tensor([[1., 1.],
        [1., 1.]])
torch.float32


De base, les tenseurs sont de type *torch.float32*. On peut toutefois les convertirs avec *dtype* :

In [47]:
x = torch.ones(2,2, dtype=torch.double)
print(x.dtype)
x = torch.ones(2,2, dtype=torch.float16)
print(x.dtype)
print(x.size())

torch.float64
torch.float16
torch.Size([2, 2])


- Convertir une liste en tenseur :

In [48]:
liste = [2.5, 0.1, 29]
x = torch.tensor(liste)
print(x)

tensor([ 2.5000,  0.1000, 29.0000])


Addition/soustraction/multiplication/division avec PyTorch

In [50]:
x = torch.rand(2, 2)
y = torch.rand(2,2) 
print(x + y)
print(torch.add(x,y))  # Exactement pareil à x+y
y.add_(x)  # On vient redéfinir y en ajoutant x. Les opérations avec _ redéfinisse la variable
# x * y ou torch.mul pour multip | x / y ou torch.div pour division

tensor([[1.5690, 1.3868],
        [0.3750, 1.5473]])
tensor([[1.5690, 1.3868],
        [0.3750, 1.5473]])


tensor([[1.5690, 1.3868],
        [0.3750, 1.5473]])

In [70]:
#Slicing
x = torch.rand(5,3)
print(x)
print(x[:,0])  #x[ligne:colonne] -> x[:,0] = On veut toute la colonne 0
print(x[1,:]) #Ligne 1 avec toutes les colonnes
print(x[1,1])  #Élèment à la position (1,1)
print(x[1,1].item())  # Permet d'avoir la valeur exacte. Fonctionne pour 1 tenseur à 1 terme seulement

tensor([[0.6783, 0.7785, 0.6247],
        [0.2020, 0.9870, 0.0875],
        [0.4326, 0.5474, 0.0277],
        [0.3054, 0.9637, 0.7080],
        [0.2614, 0.9378, 0.9006]])
tensor([0.6783, 0.2020, 0.4326, 0.3054, 0.2614])
tensor([0.2020, 0.9870, 0.0875])
tensor(0.9870)
0.9870083928108215


Reshape un tenseur :

In [87]:
x = torch.rand(4,4)  # Total 16 valeurs
y = x.view(16)  # Remet les 16 valeurs en 1 ligne
y = x.view(2,2,2,2)  # Remet les 16 valeurs en 2 lignes
z = x.view(-1, 8)  # Trouve la bonne grosseur du tenseur avec 8 termes/lignes
print(y)
print(z)

tensor([[[[0.3817, 0.2854],
          [0.6098, 0.8032]],

         [[0.4815, 0.9390],
          [0.7699, 0.6433]]],


        [[[0.3229, 0.6010],
          [0.2862, 0.5417]],

         [[0.0583, 0.7235],
          [0.9591, 0.9337]]]])
tensor([[0.3817, 0.2854, 0.6098, 0.8032, 0.4815, 0.9390, 0.7699, 0.6433],
        [0.3229, 0.6010, 0.2862, 0.5417, 0.0583, 0.7235, 0.9591, 0.9337]])


**Convertir Torch en Numpy et vice-versa**

In [90]:
a = torch.ones(5)
b = a.numpy()  # Devient numpy
print(type(b))

a.add_(1)
print(a)  # Attention : On a modifié a, mais b est quand même modifié car
print(b)  # il partage la même place dans le gpu

<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [92]:
a = np.ones(5)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)  # Attention : b a aussi été changé
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [96]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y  # Performe sur le GPU
    # On ne peut pas faire de z.numpy() car numpy ne fonctionne pas sur GPU
    z = z.to("cpu")

nop


**Tutoriel #2 : Autograd**

Calculer des gradients dans PyTorch

In [3]:
x = torch.randn(3, requires_grad=True)  # rand -> Retourne tenseur avec nombres aléatoires avec distribution normale. sigma=1 mu = 0
print(x)                                #requires_grad informe que nous voulons calculer le gradient

y = x + 2  # Voir dessin (1)
print(y)  #grad_fn car output, add car addition et Backward car backpropagation

z = y*y*2
print(z)  #grad_fn car output, mulbackward car multiplication
z = z.mean()   #grad_fn = <MeanBackward>
print(z)

z.backward()  #dz/dx

print(x.grad)

tensor([ 0.2926,  2.2143, -0.7689], requires_grad=True)
tensor([2.2926, 4.2143, 1.2311], grad_fn=<AddBackward0>)
tensor([10.5124, 35.5209,  3.0312], grad_fn=<MulBackward0>)
tensor(16.3548, grad_fn=<MeanBackward0>)
tensor([3.0569, 5.6191, 1.6415])


Ici, *requires_grad=True* permet de calculer un Jacobien vectoriel. Pour ce faire, il faut spécifier un vecteur $\vec{v}$ avec lequelle nous allons calculer le jacobien. Plus haut, nous n'avons pas spécifier de vecteur car nous faisions le backward() d'une valeur (moyenne de z). Si on veux faire le backward() de z:

In [115]:
x = torch.randn(3, requires_grad=True)
y = x + 2
z = y*y*2

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)

z.backward(v)  #dz/dx
print(x.grad)

tensor([1.3694, 7.1130, 0.0095])


Si l'on veut ne pas calculer le jacobien pour certaines opérations, il est possible de le faire ainsi:

In [ ]:
x = torch.randn(3, requires_grad=True)

y = x.detach()  #Crée un nouveau tenseur y qui ne comptera pas dans le calcul du jacobien

with torch.no_grad():
    # Insérer calcul ici
    y = x + 2

Calculer un gradient dans une boucle for

In [117]:
weights = torch.ones(4, requires_grad=True)

for _ in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)  # Si on arrête ici, le gradient va se remplir et on va constater que les gradients se sommes

    weights.grad.zero_()  #Remet le gradient à 0. On doit le faire après chaque calcul de gradient

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
